version: "3"

volumes:
  db: # mount it internally instead of a folder. it avoids file lock problems

services:
  app:
    container_name: nestjs-socket
    restart: always
    build: .
    network_mode: host
    environment:
      - PORT=3004
      - TZ=Asia/Ho_Chi_Minh
    ports:
      - "3004:8000"
  redis:
    image: "redis:alpine"