version: "3"

volumes:
  db: 

services:
  app:
    container_name: nestjs-socket
    build: .
    environment:
      - PORT=3004
      - TZ=Asia/Ho_Chi_Minh
    ports:
      - "3004:8000"
    depends_on:
      - redis
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"